// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import type { PrismaConfig } from "prisma";
import { defineConfig, env } from "prisma/config";

export default {
  schema: "src/database/schema.prisma",
  migrations: {
    path: "src/database/migrations",
    seed: "tsx src/database/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
} satisfies PrismaConfig;

// export default defineConfig({
//   schema: "src/database/schema.prisma",
//   migrations: {
//     path: "src/database/migrations",
//     seed: "tsx src/database/seed.ts",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
